### ISSUE TITLE
[Request] MXNet operator support

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/community#136]
Now we support TensorFlow and pytorch well. MXNet is another popular ML framework and I think we should implement the operator for it to attract more DL practitioners.

We need to create a proposal like https://github.com/kubeflow/community/blob/master/proposals/pytorch-operator-proposal.md and create the repository for the operator.

### References

- https://mxnet.incubator.apache.org/faq/distributed_training.html
- https://github.com/apache/incubator-mxnet/blob/master/example/gluon/image_classification.py

/cc @brucechin

**Comment by suleisl2000** [comment]
[TuSimple](http://www.tusimple.com) have just written a draft version of [MXNet operator](https://github.com/TuSimple/mxnet-operator). We'd like to contribute it to Kubeflow community as part of ecosystem and continuously improve it in the future. In addition to better deep learning lifecycle management, we plan to integrate the operator with kube-arbitrator for better job scheduling. Any process I have to follow up to make it happen? @jlewi 

BTW, TuSimple is one of the major contributors in [MXNet community](http://mxnet.incubator.apache.org/community/powered_by.html).

/cc @k82cn @jzp1025 @jjmtraveller

**Comment by jlewi** [comment]
@suleisl2000 that's a fantastic offer.

Would you and TuSimple be willing to continue supporting the operator and making the changes (see below) to better integrate it into Kubeflow? 

Assuming we go forward integrating this into Kubeflow there's a couple things we should do

1. Add a ksonnet package see [here](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/ksonnet_packages.md)
1. Add an mxnet guide to our website [here](https://github.com/kubeflow/website/tree/master/content/docs/guides/components
1. Figure out where the code should live
1. Figure out what changes are needed to provide an API consistent with other operators see kubeflow/pytorch-operator#49

@suleisl2000 @johnugeorge is currently working on refactoring the PyTorchJob and TFJob operators so that they can share implementation; see for example kubeflow/tf-operator#773. The current thinking is that we should have a different CRD for each type of job, but the underlying implementation should be shared.

As part of this there is ongoing discussion about whether we should use separate repos or move all the 
code into a single operator.

@gaocegege @johnugeorge what do you think? Should we put the code in its own repository or should we add it to tf-operator to make it easier to start refactoring to use a shared implementation?

**Comment by johnugeorge** [comment]
@suleisl2000 Great to see this effort.  Tf-operator is currently refactored to share the common code for future operators. Operators will have their own CRDs(at least for now) while sharing all common code.  Currently, we have decided to use tf-operator as the central repo to hold all operators.  We have planned to rename the repo in the future. I will raise initial PR for Pytorch operator(v1alpha2) in a week. You can use that as a reference.  

@jlewi 
Since we already have a shared implementation now,  I think we should use it.  Else efforts will be duplicated. we can plan v1alpha2 version of https://github.com/TuSimple/mxnet-operator to use the shared implementation in tf-operator repo.

**Comment by suleisl2000** [comment]
@jlewi @johnugeorge Thanks for your reply. We are glad to integrate it into Kubeflow and we will take actions as following:
1. Investigate v1alpha2 version to use shared implementation mentioned by @johnugeorge 
2. Finish TODO items listed by @jlewi 

/cc @jzp1025 @jjmtraveller

**Comment by jlewi** [comment]
SGTM. I think if we do items 1 (ksonnet package) and 2 (docs) people can start using it and giving feedback. As long as we mark it "experimental" to indicate that is in flux and subject to change I don't see a strong need to block on resolution of i/how best to integrate into the shared implementation.

**Comment by suleisl2000** [comment]
@jlewi That's great. We are cleaning up the code, and will create a PR once it done.

**Comment by suleisl2000** [comment]
I have created PRs for [ksonnect package](https://github.com/kubeflow/kubeflow/pull/1392) and [docs](https://github.com/kubeflow/website/pull/172). However, I am not sure how to create PR for [the operator](https://github.com/TuSimple/mxnet-operator), would you mind giving some guidance? @jlewi @johnugeorge

**Comment by jlewi** [comment]
What's the question about the operator; is it just about where to put the code? Should ew create a new repository for this?

**Comment by suleisl2000** [comment]
Yes, that's my question. Currently, we have the repository under https://github.com/TuSimple/mxnet-operator. I think it is better to move the code into https://github.com/kubeflow just like other operators. If it is the case, who have the permission to create the repository for it? @jlewi

**Comment by johnugeorge** [comment]
Yes. Sounds good @jlewi

**Comment by gaocegege** [comment]
I think we could create a new repo. Repo transfer requires the ownership in Kubeflow and TuSimple org

**Comment by jlewi** [comment]
I think a new repo is better; just so there is a PR indicating CLA's been signed and code is contributed.

**Comment by jlewi** [comment]
@suleisl2000 I have created the repo mxnet-operator.
I also sent you an invite to the org please accept.

You'll need to do the following

1. Follow the instructions here to setup Prow
    * https://github.com/kubeflow/community/blob/master/repository-setup.md#setting-up-prow-for-your-repository
1. Add other reviewers/approvers to the OWNERs file as necessary (they will need to request invites to the Kubeflow org for that to actually work)
1. Please submit a PR adding yourself to members.yaml 
    https://github.com/kubeflow/community/blob/master/members.yaml
    so that we know how to reach you
    * All the repo approvers should also be listed there; everyone should submit a PR for themselves so its clear we have their permission to include them in the repo.
1. You should be able to submit and approve PRs to the repo
    * For more info https://github.com/kubeflow/community/blob/master/CONTRIBUTING.md

Lets leave this issue until the above items are completed and the repo is fully setup.

**Comment by idibidiart** [comment]
Really eager to try MXNet Operator in Kubeflow. Is it ready in master? @suleisl2000

**Comment by suleisl2000** [comment]
There is a little bit merge effort to be done. I will try to finish it early next week. Thank you for your attention. @idibidiart

**Comment by jlewi** [comment]
@suleisl2000 I already added the ci-bots; sorry for not making that clear.

sent @jzp1025 a GitHub invite.

**Comment by gaocegege** [comment]
Could we close the issue? I think the mxnet operator repository has been set up.

**Comment by idibidiart** [comment]
Hi,

Has it been merged with master? Or is it a separate repo?

Also, is there a Readme for using MXNet with Kubeflow?

**Comment by gaocegege** [comment]
I think we could close the issue since we have the repo for mxnet operator.
