### ISSUE TITLE
Request to move KVC repo over to IntelAI org. 

### ISSUE THREAD

**Issue by balajismaniam** [kubeflow/community#138]
Offline, @jlewi and I discussed about moving the KVC repo (https://github.com/kubeflow/experimental-kvc) over to the IntelAI org (https://github.com/IntelAI). Jeremy suggested that I open an issue here to document the request.

**Comment by jlewi** [comment]
Is there any additional work that needs to happen; e.g. update examples, ksonnet packages?

**Comment by jlewi** [comment]
Here's the original request:
https://github.com/kubeflow/community/issues/16

@elsonrodriguez Can you please ack since you filed the initial request?

Also are there any contributors to experimental-kvc that have a problem with this?
https://github.com/kubeflow/experimental-kvc/graphs/contributors

In particular are there any non Intel contributors who want to weigh in?

**Comment by balajismaniam** [comment]
> Is there any additional work that needs to happen; e.g. update examples, ksonnet packages?
In Elson's example for S3 tf.data is being used. So there is no change required there. The ksonnet packages need not be changed.

**Comment by jlewi** [comment]
The [owners](https://github.com/kubeflow/experimental-kvc/blob/master/OWNERS) lists

  * @balajismaniam 
  * @elsonrodriguez 
  * @jose5918 
  * @Ajay191191

My opinion is that moving KVC out of Kubeflow makes sense because its a generic storage component that isn't ML specific and lower level than Kubeflow.

So I support whatever the owners listed above. Can the owners listed above please chime in?

@balajismaniam I'd also suggest dropping a line to kubeflow-discuss@googlegroups.com to point folks at this issue.

Would you mind also waiting at least 24 hours just to give people a chance to respond?

**Comment by balajismaniam** [comment]
Sure @jlewi, we can wait 24 hours. I will email kubeflow-discuss mailing list.

**Comment by jlewi** [comment]
Thanks @balajismaniam. You and the other Intel team members are already admin's on the repository so I believe you should be able to request a transfer.

At the risk of being pedantic I would like an explicit ack on this issue from @elsonrodriguez and (ideally all the owners listed in the owners file) before doing the transfer. I think its good practice to leave a paper trail indicating consensus.

Consider this my /lgtm, assigning this to you.

/assign @balajismaniam

**Comment by balajismaniam** [comment]
@jlewi Thanks. We can wait for acks from more owners. Regarding the transfer, it seems like only org owners can initiate transfers (org members cannot).

**Comment by elsonrodriguez** [comment]
I'm out of the loop on this one, I'll defer to @nqn

**Comment by nqn** [comment]
@jlewi It's a LGTM, if that carries any weight

**Comment by Ajay191191** [comment]
LGTM

**Comment by jlewi** [comment]
GitHub only allows me to transfer to myself; I didn't have permissions in IntelAI.org
I transferred it to me with the intent of transferring it to balajismaniam 
But that failed because balajismaniam/experimental-kvc exists
@balajismaniam Can you rename your existing repository so I can transfer to you.

**Comment by balajismaniam** [comment]
@jlewi I changed the name of my fork. Please try again.

**Comment by jlewi** [comment]
Repository has been transffered to @balajismaniam

**Comment by balajismaniam** [comment]
I transferred it to the IntelAI org. Thanks @jlewi.
