### ISSUE TITLE
Create kubeflow/experimental-kvc to house an S3 data management utility

### ISSUE THREAD

**Issue by elsonrodriguez** [kubeflow/community#16]
We have a use-case where we'd like data local to the training processes to maximize throughput, but the datasets are in s3.

We've written a controller to manage these datasets and download them to nodes, which can then be bindmounted into a container, and would like to open source it under the kubeflow org.

Please  create `kubeflow/experimental-kvc` to house this project.

Also proposing that we use the `experimental-...` pattern for other similar helper projects.

**Comment by jlewi** [comment]
I've created the repository to unblock you.

I also created the team Intel and given it write access to the repository. You are a maintainer so you should be able to add any colleagues at Intel. 

I'll leave this issue open for now to give folks an opportunity to comment in case they think there should be more process before creating experimental projects.

My two cents is we should have a pretty low bar for experimental and then at some point a project should go through the proposal process and graduate to something like "incubating" or be deleted.

**Comment by jlewi** [comment]
Kubeflow should be Cloud agnostic and K8s native. So eventually we will need to make the tool work everywhere K8s runs and not just with S3.

I believe Pachyderm does something similar; i.e. copies data to/from the pod to Pachyderm's data store.

Could this be implemented as volume plugins? So pods could just mount a volume or PVC and the volume plugin/controller would take care of actually making the data available to the pod?

/cc @dwhitena

**Comment by dwhitena** [comment]
Indeed @jlewi. Here's what Pachyderm already does, which might help put some of this in context based on our experience trying this:

Pachyderm's data is backed in any generic object store (we have an internal object store package that utilizes one of a few object store clients under the hood, for Azure, GCS, and any S3 compatible API). That gives us the flexibility to back the data for data pipelines anywhere in the cloud or on prem.

There is a "worker" binary that is shimmed into the user containers that run as Pachyderm pipeline stages. When `pachd`, our server, determines that a job needs to run it initiates the worker binary. The binary then downloads the data for the job (as determined by `pachd`) using the Pachyderm client to `/pfs` in the user container, and it runs the command specified by the user (e.g., running some python script). Once the command finishes, the worker binary slurps up all the data in `/pfs/out` as output and sends it back to Pachyderm via the client.

There is also a way that data can be accessed lazily in Pachyderm. In this case, the worker binary exposes the data as named pipes rather than actively downloading it to the user container. 

Hope this helps give some context. We are currently experimenting and exploring a way to extend this functionality into KubeFlow TFJobs. That way we could trigger and control TFJobs from a Pachyderm pipeline, which would give us the ability to have versioned, scalable ML pipelines on top of KubeFlow (or at least one option for this).

**Comment by elsonrodriguez** [comment]
Thanks for the repo!

As @dwhitena mentioned s3 is the lingua franca when it comes object stores, which is why we chose it. For the first pass a https://github.com/kubeflow/examples/issues/2 we're just using the aforementioned simple utility to sync the data, but we'd be happy to checkout or help with Pachyderm for a follow-up example.
