### ISSUE TITLE
Setup Documentation site

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#21]
Opening an issue to figure out what we want to do about a documentation site.

Do we want to use  GitHub pages?
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

Are there alternatives?

**Comment by ewilderj** [comment]
I'm very interested in the idea of using [Hugo](https://gohugo.io/) and checking the site into source control. It would provide for future scalability with [things like](https://gohugo.io/about/features/) localization (almost always near impossible to retrofit, and I think we want to have Chinese docs as well as English in the near future) without too much initial overhead, and the ultimate in portability (just files). Hugo actually works with Github Pages too.

I need to convene the outreach & education SIG who could be an owner for this!

**Comment by jlewi** [comment]
/assign @ewilderj 

@ewilderj Do you want to take this and figure out who should own it?

**Comment by ewilderj** [comment]
cc @nickchase for discussion

**Comment by ewilderj** [comment]
Nick and I are making progress and are assembling team, putting together a backlog
Working doc is https://docs.google.com/document/d/1XUGnLVCyqVLN62VWqk-o_FLhRU1L4b7VRcwP8QgFst4/edit#

**Comment by ewilderj** [comment]
Web site repo is now created, looking for people to be part of the team.

Other news:

I spoke with the design team at EggsandRice, the agency Google Cloud uses. We asked for a design that could work for Kubecon and beyond.

The optimal path probably lies along using a Hugo theme that we like, or proposing several, and they would provide customization to that with things that fit the colors, fonts, etc they choose for the new logo.

I like the look of https://themes.gohugo.io/kube/ — but I'm not yet sure of the technical implications of choosing one theme over another, we ought to do a bit of due diligence before committing.

Web team conversation is now here: https://groups.google.com/a/kubeflow.org/forum/#!topic/web-team

Ask to join that group in order to join the team!
