### ISSUE TITLE
Use stackalytics to track contributions from different company

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/community#222]
We have just enabled stackalytics to track the contributions from different companies for kubeflow at http://stackalytics.com/?project_type=kubeflow-group&release=all&metric=commits

stackalytics is becoming an official website for open source contributions, like openstack, kubernetes, istio etc, so it would be great if we can use it for kubeflow as well.

More discussions are here https://github.com/kubeflow/community/issues/125#issuecomment-448114451

/cc @jlewi @theadactyl

**Comment by jlewi** [comment]
@gyliu513 What do mean stackalytics is becoming an official website for open source contributions? is the kubernetes or CNCF endorsing it as the way to get metrics for their projects?

**Comment by gyliu513** [comment]
Kubernetes and CNCF is not endorsing it, the stackalytics was originally designed for calculating OpenStack contributions https://wiki.openstack.org/wiki/Stackalytics , but it was now gradually growing up for more open source, like Kubernetes, Istio etc, but I do not know when Kubernetes was added as part of stackalytics. ;-)

**Comment by jlewi** [comment]
I have a preference for https://github.com/cncf/devstats since its

1. Maintained by CNCF
1. Is used by all CNCF projects
1. Would hopefully give us a single solution for all our stats.

So my preference would be to invest in fixing our devstats instance to properly show contributions by company.

That said I think the bigger blocker to using Stackalytics is that I think it will require most contributors to submit a PR to OpenStack to set their affiliation. I think we have lots of contributors not using their corporate email with their GitHub accounts. 

I'd like a solution that takes into account the company as set in the user's GitHub profile. 

It looks like OpenStack isn't using GitHub (https://review.openstack.org/#/c/625774/) (looks like Gerrit). So asking our contributors to summit a PR means asking them to figure out how to use another code review system; it would be great if we could reduce this friction.

/cc @theadactyl

**Comment by gyliu513** [comment]
> It looks like OpenStack isn't using GitHub (https://review.openstack.org/#/c/625774/) (looks like Gerrit). So asking our contributors to summit a PR means asking them to figure out how to use another code review system; it would be great if we could reduce this friction.

@jlewi But if you submit your PR via the email address of your company, then you do not need to submit a PR, such as if I submit with email as `xx@cn.ibm.com`, then I will belong to IBM contributors.

**Comment by jlewi** [comment]
@gyliu513 understood but I think a lot of people aren't using corporate email addresses but their profile will list their company.

**Comment by gyliu513** [comment]
@jlewi Yes, I see, then I think we can let developers make their decision, as we have both https://www.stackalytics.com/unaffiliated?project_type=kubeflow-group and https://github.com/cncf/devstats , they can select the one that they like.

As I was not going to update https://www.stackalytics.com/unaffiliated?project_type=kubeflow-group anymore and it will be there as it is now, we can continue to enhance https://github.com/cncf/devstats as we want.

**Comment by jlewi** [comment]
Sounds good.

**Comment by gaocegege** [comment]
I think we can close the issue now.
/close
