### ISSUE TITLE
Create a kubeflow/metadata repository

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/community#238]
It looks like metadata management should be a kubeflow component of its own. We need a repository e.g. `kubeflow/metadata` for its design proposals, api and schema docs, and implementations.

**Comment by animeshsingh** [comment]
**metadata** gives it a much wider connotation. Better would be to call it **metadata-store**. Also we would love to collaborate on this one

**Comment by mpvartak** [comment]
Few thoughts:

- Having a KubeFlow "native" metadata repo will make this metadata implementation the de-facto implementation for metadata in the KF ecosystem, whether/not it turns out to be the best implementation. 

- A KF metadata repo lowers the incentive for 3rd party developers to build a metadata store that will work with KubeFlow because it's not clear why a user should use a third-party vs. a pre-bundled metadata store. 

- As a parallel, there could have been a "Serving" repo in KF but there isn't a pre-specified serving component. This has allowed multiple serving components like Seldon, OpenVino, TFServing to be available. Having an official metadata store will essentially makes KF less open as a platform/framework

- Operationally, I understand the need to organize metadata efforts, but we should consider its impact on current and potential integrators into KF and signaling going forward. 

- Have a single spec for metadata seems more valuable compared to a single implementation repo as it will allow for multiple implementations.

**Comment by zhenghuiwang** [comment]
@mpvartak Thanks for bringing up the concerns! Here are my clarifications.

> * Having a KubeFlow "native" metadata repo will make this metadata implementation the de-facto implementation for metadata in the KF ecosystem, whether/not it turns out to be the best implementation.
> * A KF metadata repo lowers the incentive for 3rd party developers to build a metadata store that will work with KubeFlow because it's not clear why a user should use a third-party vs. a pre-bundled metadata store.

The purpose of this repository is not to have everyone use one single implementation but accommodate  multiple implementations. Users should be able to choose one implementation when installing the Kubeflow cluster, because it is impossible to have everyone uses the same database.

> * As a parallel, there could have been a "Serving" repo in KF but there isn't a pre-specified serving component. This has allowed multiple serving components like Seldon, OpenVino, TFServing to be available. Having an official metadata store will essentially makes KF less open as a platform/framework

Serving is a relative independent component. The interface is clear: this is my model file, serve it. But metadata is about understanding the data produced by multiple components in KF. So we have to define the meaning and interface of metadata ourselves.

> * Have a single spec for metadata seems more valuable compared to a single implementation repo as it will allow for multiple implementations.

It is good to have a metadata schema that everyone agrees on. It is even better to have a server API as a concrete reference to how the schema can be used. The metadata store should be closed for API changes but open for more implementations.

**Comment by aronchick** [comment]
Correct me if I'm wrong, but I think we are talking past each other.

I don't BELIEVE @mpvartak is saying that we should have a single metadata solution across Kubeflow. I think she's saying the metadata (the spec, not the implementation) should be separate.

Right now, the Kubeflow team is proposing keeping them together, and keeping them both in the Kubeflow repo. I think this will be a problem, and will necessarily hurt the adoption of Kubeflow's metadata schema (not implementation). Could you imagine, for example, the TFX team being comfortable using the metadata schema from the Kubeflow repo?

**Comment by zhenghuiwang** [comment]
I think @mpvartak's major concern is the "native" metadata store implementation lowers the incentive for 3rd parties to contribute to KF metadata store. I want clarify there won't be a single implementation with one particular DB/framework, but multiple implementations that users can configure during installation. So that 3rd parties still have incentives to contribute to implementations of APIs defined in this repo.

>  Right now, the Kubeflow team is proposing keeping them together, and keeping them both in the Kubeflow repo. I think this will be a problem, and will necessarily hurt the adoption of Kubeflow's metadata schema (not implementation). Could you imagine, for example, the TFX team being comfortable using the metadata schema from the Kubeflow repo?

I think it is hard for other open source projects to adopt spec under Kubeflow anyway. (IIRC that is the motivation for #239 ) So having `kubeflow/metadata-spec` and `kubeflow/metadata-store` as two separated repo won't help the adoption of Kubeflow metadata spec.

I think we can use this repo for metadata schema and store implementations in Kubeflow. If there is a repo for standard ML metadata schema,  we can sync the spec in these two repos.

**Comment by jlewi** [comment]
+1 to @zhenghuiwang's comments.

@mpvartak @aronchick  could you help me understand your problem

1. Are you ok with creating a new repository in Kubeflow for metadata related efforts?
1. Would you prefer a different name to `kubeflow/metadata` ?
1. Does creating a separate repo or org to host just the metadata specs need to block creating a new repo in Kubeflow to store metadata related code?  
    * If we don't start putting code into a Kubeflow repo, where should it go and how do we unblock development?

**Comment by mpvartak** [comment]
@jlewi, @zhenghuiwang, @aronchick, here are some thoughts and a proposed solution.

My main concern is that a Kubeflow-native metadata store implementation in Kubeflow dis-incentives 3rd parties to contribute to Kubeflow metadata store. Abhishek gave the example of WandB as a 3rd party who has a solution that can work with Kubeflow. The challenge here is that discovering these alternatives is super hard (e.g., I didn't know WandB even worked with Kubeflow) because there is no indication in the Kubeflow repo. 

I'm good with a metadata repo, my main ask is to make this a community-driven effort that keeps metadata module flexible/open for other components. I think this can happen in parallel with the broader MLSpec efforts.

Specifically, I'd recommend:
- Have a schema/api folder in this repo with the KF schema. Ideally, this would be the same schema as David is describing in #239
- Have an implementations folder where Kubeflow, TFX, other 3rd parties can register/provide their implementations. 
- Have an easy way for users to find alternative components (discoverability)
- Have other components in KubeFlow use the schema defined in the api folder vs. talking directly to specific implementations

More generally, @animeshsingh had a really great comment at the PM group last week which has to do with what Kubeflow wants to be in the long term: a) an opinionated version of an ML framework or b) a composable and extensible ML framework. I believe this is really what we are talking about. To support vision b) -- which I think is the goal of Kubeflow -- I believe separating apis and impls of components will be key and metadata is just the start.

PS: It looks like Kubeflow serving is going through a similar discussion would be worth seeing how they are handling this decision

**Comment by mpvartak** [comment]
Also, along with helping with the schema, I'm happy to help drive the discoverability of modules.

**Comment by zhenghuiwang** [comment]
IMO Kubeflow is supposed to be an open platform that every ML framework can be part of it, which in turn makes Kubeflow more appealing to end users. Building a community owned metadata API layer is an important step for KF components to leverage each other. Seems we are in an agreement here.

> Have a schema/api folder in this repo with the KF schema. Ideally, this would be the same schema as David is describing in #239
> Have an implementations folder where Kubeflow, TFX, other 3rd parties can register/provide their implementations.

This is also how I envision the structure of the repository.

> Have an easy way for users to find alternative components (discoverability)

That's also my goal but I haven't put too much thought on it. Happy to have you help drive it.

> Have other components in KubeFlow use the schema defined in the api folder vs. talking directly to specific implementations

Definitely want other components to talk to the API.

**Comment by aronchick** [comment]
To follow up on @mpvartak's & @zhenghuiwang's points, and I think splitting the difference for what @jlewi wants, we should have an *external* repo for the general schema, and then a kubeflow/metadata repo that represents the Kubeflow specific metadata that is an implementation of the external schema.

**Comment by neuromage** [comment]
+1 on improving discoverability of components. Maybe kfctl is the right place for this, as this is how users choose what components to deploy. Good and up-to-date documentation on kubeflow.org can help here as well.

I don't think however it's a good idea to have multiple implementations under a directory in the same repo. I'd prefer if each repo is a cohesive collection of code and assets that work together towards realizing a single implementation. It also makes issue tracking and project planning within implementations easier. Creating a repo isn't expensive, and I don't think we'll have that many implementations for this to be an issue. We can certainly host the API definition itself in another repo as well if needed. 

If the concern is that /metadata is too general, we can rename the repo to kf-metadata, and have similar ones like /modeldb-metadata etc (or something along those lines).

I would also argue that there is more value in defining a common schema vs an API, so multiple tools can inter-operate through shared understanding of the representation of ML artifacts. Implementations can be optimized to do different things, each with its own strengths, depending on how the underlying implementations. Therefore I think there is more benefit for the community in having a shared schema vs having a shared implementation API.

**Comment by animeshsingh** [comment]
> we should have an _external_ repo for the general schema, and then a kubeflow/metadata repo that represents the Kubeflow specific metadata that is an implementation of the external schema.

+1. This should be right structure. A metadata org/repo outside of kubeflow org for defining the schema, and kf-metadata-store in kubeflow ord, and modeldb-metadata-store in modeldb org

**Comment by zhenghuiwang** [comment]
https://github.com/kubeflow/metadata now exists.

Let's move the discussion on specific issues in that repository.
