### ISSUE TITLE
Discussion: Move section 7.1 (all metadata schema) to its own non-Kubeflow based organization

### ISSUE THREAD

**Issue by aronchick** [kubeflow/community#239]
One of the goals of this project is to get as many ecosystem participants to agree on the metadata schema to ease interoperability between different projects. These may include non-Kubeflow projects, but all projects will benefit if the schemas are similar.

In order to facilitate this, I propose we move the items in section 7.1 of the [proposal](https://docs.google.com/document/d/104jv0BvQJ3unVEufmHVhJWgUAqJOk2CwsCpk5H5vYug/edit#) to its own organization/repo. I've been playing around with the name "MLSpec" but I'm open to whatever everyone thinks would be good. 

This shouldn't slow Kubeflow's metadata project at all! Just separate out some items which couple everything too tightly today.

cc @amygdala who also had some thoughts

**Comment by aronchick** [comment]
cc @zhenghuiwang @abhi-g

**Comment by cliveseldon** [comment]
Makes sense to me. Then a kubeflow repo could provide a reference implementation.

**Comment by jlewi** [comment]
Setting up and maintaining a GitHub organization is a non-trivial amount of work. Some work off the top of my head

* Setting up CLA checks
* Setting up test-infra
* Maintaining org permissions and invites

The last one is a big one since it creates work for potential contributors as well as the maintainers of the org.  For Kubeflow we've been making steady progress to automate this using prow.

Is there a reason to incur the cost of setting up and maintaining a separate GitHub org now?

Suppose we start developing the metadata in Kubeflow owned repo, isn't it relatively straightforward to move those into an upstream repo if and when we are ready?

Transferring a repo between organizations is pretty trivial.  We've done this for a number of repositories; transferring them in and out of Kubeflow.

**Comment by jlewi** [comment]
kubeflow/community#238 is the issue to setup a repo for metadata.

**Comment by aronchick** [comment]
Correct - but these are two separate issues. The metadata management code/servers, etc, should exist inside Kubeflow, since they are Kubeflow specific. 

The metadata schema should exist outside of Kubeflow, since it is NOT Kubeflow specific.

**Comment by mpvartak** [comment]
+1 for separating the spec from the implementation (whether in the same repo/separate). More thoughts here: https://github.com/kubeflow/community/issues/238#issuecomment-474221268

Essentially having a single official metadata implementation will disincentivize third-party metadata tools from integrating with KF. On the other hand, if there are multiple implementations of the same spec, users can pick and choose the one that fits their needs best -- making the platform more flexible and open.

**Comment by jlewi** [comment]
If the schema exists outside Kubeflow who is going to own and administer it?
