### ISSUE TITLE
Discussion: Have an standard "extension/custom" section for each metadata component

### ISSUE THREAD

**Issue by aronchick** [kubeflow/community#240]
Rather than asking every platform to agree on every spec, perhaps it would be valuable to have a "standard" place for people to but information for their particular platform. E.g.

Run for Platform A:
```
id: xxx
artifacts:
- aaa
- bbb
project: xxx
annotations: xxx
custom:
- platform_a_custom_1:
-- aaa
-- bbb
- platform_a_custom_2:
-- aaa
-- bbb
```

Run for Platform B:
```
id: xxx
artifacts:
- aaa
- bbb
project: xxx
annotations: xxx
custom:
- platform_b_custom_1:
-- ccc
-- ddd
```

Basically, all I'm suggesting is that we think about a standard field into which platform providers can extend their own metadata, while still leaving the rest of the metadata as a standard.

**Comment by aronchick** [comment]
cc @zhenghuiwang @abhi-g

**Comment by zhenghuiwang** [comment]
I agree it is a good idea to have a standard field that different platform providers can extend. 

Can't we use`annotations` as the standard field? I view annotations as `map<string, string>` so that you can have `annotation['platform_a'] = <JSON serialized string>`.

What's the type of `custom` field?

**Comment by aronchick** [comment]
Annotations works! I just think the naming of that field makes it kind of confusing (can't think of a better name though)

Agree it should be a map<string, string> type
________________________________
