### ISSUE TITLE
WG Sponsorship for central dashboard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#380]
Per the governance discussions. All projects need to find WG sponsorship or they will eventually be archived.

Opening this issue to begin discussions about what to do about the central dashboard.

/cc @avdaredevil @prodonjs @swiftdiaries @StefanoFioravanzo @SachinVarghese

**Comment by swiftdiaries** [comment]
I'll be happy to chair the UI WG. I'll let the others decide what level of commitment they want to bring to the WG

**Comment by StefanoFioravanzo** [comment]
@jlewi  @swiftdiaries  I would definitely be happy to co-lead this WG, as noted in the original WGs PR

**Comment by SachinVarghese** [comment]
I am also happy to co-lead this WG.

**Comment by jlewi** [comment]
@swiftdiaries @SachinVarghese @StefanoFioravanzo What would the scope and charter be for the UI WG? Why would we have a horizontal WG for UIs as opposed to making each project and its corresponding WG responsible for its OWN UI?

Are there any opportunities to merge or replace central dashboard with something upstream that is generic and not Kubeflow specific?

The primary purpose of centraldashboard is to provide a portal to navigate between a bunch of different web applications running on your KF cluster. This isn't really Kubeflow specific. 

Spotify for example has created https://github.com/spotify/backstage?

cc @Rugvip @benjdlambert

**Comment by swiftdiaries** [comment]
Hey @jlewi 

I started https://github.com/mlbackstage/mlbackstage to explore the possibility of having a generic ML developer portal. It's still super early. And I'm kinda working out the idea down to how best we can integrate/adopt.
My initial idea was to have each application own a plugin for Kubeflow. For example, the notebooks CRD would be backed by a Notebooks plugin. The KFServing CRD would be backed by a KFServing plugin and so on for the rest of the individual applications.

So Kubeflow and it's applications would become a set of plugins that play well with other ML-based tooling in an organisation. I'm kind of unsure whether it makes sense to have a ML-specific developer portal.

**Comment by swiftdiaries** [comment]
I think Spotify internally has a set of ML plugins as part of their internal Backstage along with their other plugins. So ML Backstage might be an anti-pattern

**Comment by stefanalund** [comment]
👋 I'm the Product Manager for Backstage and wanted to provide my 2 cents.

@swiftdiaries as you say, creating a dedicated "Backstage" platform for ML kind of defeats the original purpose of Backstage as an aggregation platform (a "platform of platforms" of sorts).

Inside Spotify our ML infrastructure team(s) are building plugins for Backstage itself. Having ML tooling integrated into our single developer portal makes ML, and other tools, more accessible to a wider audience -- even lowering the bar for people that are not ML engineers, but that want to leverage ML in their products.

From a [Backstage open source](https://github.com/spotify/backstage) perspective we would _love_ to see Kubeflow and other ML tools be integrated in Backstage as plugins.

I don't know how specifically Kubeflow relates to our internal ML plugins, but I think @jlewi or @jbx can provide more details.

**Comment by avdaredevil** [comment]
I am happy to provide oversight to bigger PRs where Central-Dashboard expertise is required :)

**Comment by swiftdiaries** [comment]
@stefanalund @jbx Would you be open to demo'ing Backstage with a short walkthrough on how Spotify does ML services within Backstage in a community meeting?

**Comment by StefanoFioravanzo** [comment]
@jlewi Interesting discussion, I have taken a quick look at backstage and my only concern would be that adopting such a solution in place of our custom central dashboard would make Kubeflow more a "collection" of microservices rather than a cohesive platform. I think the central dashboard purpose should be to bring together all the Kubeflow components, making it look like a unified product.

**Comment by swiftdiaries** [comment]
@StefanoFioravanzo from an end-user perspective I think it makes sense to have all services within their organization to show up on a single portal.
From an infrastructure provider perspective, it might look like it's better to have a single ML-specific dashboard.

So I think the centraldashboard as it is today can be evolved into a separate backstage app for infrastructure providers for a unified product. The plugins themselves can be discrete and form the building blocks for both the KF-specific central dashboard and the end-user focused Backstage app.

**Comment by SachinVarghese** [comment]
I like the idea of central dashboard evolving as a customizable plugin. It would be great to see a demo of how backstage can help in that regard and also if it is possible to easily plug kubeflow components as ML addons.  @swiftdiaries I believe you have started some initial work on this so either an initial doc or even a walkthrough from the devs at Spotify would be great to take this further.

**Comment by jbx** [comment]
Hi there - I'm missing some context on what a role a central dashboard would serve but can give you some more information about what we do at Spotify. Apologies if this is continuing to move the issue off the original subject.

At Spotify, we really only use the Kubeflow Pipelines application. We describe how we use it and what we've built in this [blogpost](https://engineering.atspotify.com/2019/12/13/the-winding-road-to-better-machine-learning-infrastructure-through-tensorflow-extended-and-kubeflow/). An update to this blog to include what we're doing with Backstage is planned later this year, but to give you an idea...

We use Backstage for the integrations with the rest of Spotify's ecosystem (managing backend services, data pipelines, documentation, etc). We built an ML plugin to track ML projects where projects may have many different types of models and models have many different Kubeflow Pipeline runs associated with them. We heavily link out to the Kubeflow Pipelines UIs instead of duplicating this information in Backstage, though we pull in pertinent information about runs that help ML teams get an initial understanding of how model performance compares against other models and how a model run might link up with a backend service.

We could give a demo at some point -- let me check with my team. In the meantime, check out this [data pipeline demo](https://www.youtube.com/watch?v=rH46MLNZIPM).

**Comment by jlewi** [comment]
It looks like we haven't made much progress on finding owners.

Per: https://github.com/kubeflow/kubeflow#4889 it looks like @avdaredevil and @prodonjs only have cycles to help out occasionally. 

Per kubeflow/kubeflow#4889 it looks like we need someone to take responsibility for releases. 
@SachinVarghese and @StefanoFioravanzo it looks like you joined the reviewers list back in July. Are you interested in taking responsibility for centraldashboard.

Alternatively we could consider removing the centraldashboard. Instead, we could default to the pipelines UI.

**Comment by thesuperzapper** [comment]
@jlewi I am pretty sure the central dashboard also has the hamburger menu for the pages (pipleines, jupyter, etc), so we cant just remove it.

**Comment by Jeffwan** [comment]
It talks to profile controller and access management as well.  This maybe part of WG-control-plane.. However, we only have WG-deployment proposal

**Comment by StefanoFioravanzo** [comment]
Yes @jlewi Centraldashboard is definitely important to ensure Kubeflow shows itself as a cohesive product. I am interested in taking responsibility

**Comment by SachinVarghese** [comment]
@jlewi I am also happy to take up responsibility for the centraldashboard project and releases. I agree with @StefanoFioravanzo on showing kubeflow as a cohesive product and centraldashboard can also be a point of other custom integrations.

**Comment by Bobgy** [comment]
centraldashboard has been added to notebooks WG: https://github.com/kubeflow/community/pull/447/files#diff-11b55409b3d27f083915bd4b910672caaf0e9550cf34d77fe76e8b6b9515023dR281
