### ISSUE TITLE
Optional-Test-Infra Documentation

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/community#450]
Given some of the kubeflow repositories have migrated to optional test-infra, which requires documentation to help them debug and onboard.

Changes need to be make against this doc 

https://github.com/kubeflow/community/blob/master/repository-setup.md

/cc @jlewi @Bobgy

**Comment by jlewi** [comment]
If a new repository is going to be using the AWS CI infrastructure that's probably a good indication that it shouldn't be created in the Kubeflow GitHub org. The Kubeflow GitHub org will continue to be administered by Google. If a repo is using AWS CI that's an indication that Google doesn't want to take on the cost of providing engprod resources to that project which includes administering repos. So the project should pick a different GitHub org so that the project owners (and not Google) take on the admin responsibilities for that repo & org.

**Comment by thesuperzapper** [comment]
@jlewi I have a proposal (which needs to be fleshed out), which will address what you are saying: https://github.com/kubeflow/community/issues/456

**Comment by PatrickXYS** [comment]
> If a new repository is going to be using the AWS CI infrastructure that's probably a good indication that it shouldn't be created in the Kubeflow GitHub org

We'll try our best to make the test-infra neutral, and it's weird that WG use optional-test-infra should be created in other org. Since we won't do the same thing to other testing tools/frameworks including Github Actions / Circle CI / Travis, what's the difference between optional-test-infra and those tools?

The goal of optional-test-infra is to provide community WG with another option for the testing tool.

> Google doesn't want to take on the cost of providing engprod resources to that project which includes administering repos

I can't see there's too much burden in Google only creating a new Github repo for a new WG, and then we can leave it to the WG.

Besides that, I'll finish the optional-test-infra documentation, focus on the engineering work afterwards.
