### ISSUE TITLE
Proposal: unbundle common cluster services

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/community#460]
Hi all,

I want to propose that we unbundle common cluster services from our [kubeflow/manifests](https://github.com/kubeflow/manifests) repo, and encourage users to install them independent of Kubeflow. This will help users upgrade Kubeflow without impacting the rest of their cluster, and make it much easier to install Kubeflow on existing clusters.

### NOTE:
* obviously our end-to-end tests will still include these services, (but in a test grid of versions which we choose to support)
* if distribution owners like AWS/GCP/etc want to include these services, they should include the versions they want, in their distribution

### I think the main services we should do this for:
* istio
* argo-workflows
* cert-manager
* knative

### Other services we probably shouldn't distribute, but rather encourage people to install if they need:
* spark-on-k8s-operator
* seldon

**Comment by thesuperzapper** [comment]
I think this decision lies with the manifests working group: @kubeflow/wg-manifests-leads

**Comment by howardjohn** [comment]
FWIW, Istio recently did essentially the same thing: https://istio.io/latest/blog/2020/addon-rework/

**Comment by PatrickXYS** [comment]
@thesuperzapper Thanks for proposal

I think this is a well-known issue, community folks already feel the pain. 

The point is, how to efficiently unbundle dependencies and meanwhile avoid breaking existing components.

But I think this should be one of the important item on our roadmap

**Comment by Bobgy** [comment]
I agree with the spirit of this proposal -- and the problem that dependency management in Kubernetes is unsolved.

I think this is a tradeoff, the more stuff we ask users to install and configure, the more likely they will face problems in manually integrating another system with Kubeflow (and it's absolutely hard troubleshooting these cases, because there's deep knowledge required). This will make it harder to install a template Kubeflow out-of-box and just use it. Especially for systems that need strict configuration integration like KFP and argo.

So I think we do not need to jump to the other extreme of not providing any of these immediately, but start by:
1. default to bundle dependencies
2. provide documentation for how to swap those dependencies out for a different version and our supported range + configuration

When we get maturer on 2 and make it as zero-config as possible, we may consider dropping 1 for each of the dependencies.

And I believe 2. is harder after using the stacks pattern in kustomize v3 efforts, I start to think:
* we did it right to not reinvent the wheels and just use kustomize
* we did it right to provide kustomize packages that correspond to conceptual applications, for example, all KFP manifests are wrapped into one kustomize package now
* but we shouldn't provide one stack for all Kubeflow applications, instead we should provide each Kubeflow application separately

**Comment by yanniszark** [comment]
@thesuperzapper thanks for taking the time to make this proposal. I am inclined to agree with @Bobgy that this is a balance between ease of installation and configurability. I believe we want both: it should be easy to deploy with little configuration AND it should be possible to swap out dependencies if necessary. We will achieve this by:
- Executing on the stated goal of wg-manifests, to provide a catalog of kubeflow + 3rd-party application manifests. This way, a user/platform can easily pick what they want.
- Each application providing clear docs on what it needs from its dependencies (e.g., Istio with support for RBAC network authz) and how to swap them in their manifests.

**Comment by thesuperzapper** [comment]
Lets keep discussing this, but I want to highlight some things:
* I don't think making this change will significantly reduce the 'ease of use', because:
   1. distribution owners can still cater to the "clean kuberntes cluster" if they want, (which is good for people who want to play around with kubeflow)
   1.  for users who have an "existing kubernetes cluster" (which will be most prod deployments), it's currently quite hard to remove cluster services from kubeflow manifests (and know what versions are supported), this change will fix that
* Its really important that Kubeflow component devs get used to not depending on a single version of components like `istio`, `knative` and `argo`, but rather a range of versions. This limitation is already hurting adoption of Kubeflow, see https://github.com/kubeflow/kubeflow/issues/5313

**Comment by thesuperzapper** [comment]
@yanniszark just wanted to check how much of the unbundling work will be completed with the `kubeflow/manifests` refactor in Kubeflow 1.3?

**Comment by thesuperzapper** [comment]
I believe most of this work has been completed with the refactor of `kubeflow/manifests` which was released in Kubeflow `1.3`
/close
