### ISSUE TITLE
Proposal: configure kubeflow/kubeflow issue template to redirect to other repos

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/community#476]
I just realized it's possible to configure issue template as generic uris, they can be links to other repos too.

https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

I think we should set it up, so that kubeflow/kubeflow issues have urls for each WG and each distribution. That will redirect users directly to the correct place.

As an example, you can look at argoproj/argo's setup: https://github.com/argoproj/argo/issues/new/choose

**Comment by Bobgy** [comment]
/cc @kubeflow/wg-notebooks-leads 
What do you think?

**Comment by Bobgy** [comment]
I remember there was some earlier discussion about this, but I didn't find the thread/issue

**Comment by Bobgy** [comment]
/cc @PatrickXYS 
who helped ping me about issues in kubeflow repo a few times

**Comment by PatrickXYS** [comment]
I think it's a good idea, we should have some redirect link to other WGs.

E.g, 

![image](https://user-images.githubusercontent.com/23116624/106699509-e3212780-6597-11eb-9799-194e3f00f3b8.png)

**Comment by PatrickXYS** [comment]
@Bobgy  Only one question here, how can we do if users are filing issues for specific cloud-providers / distributions?

**Comment by PatrickXYS** [comment]
Sent a PR to kubeflow/kubeflow https://github.com/kubeflow/kubeflow/pull/5585

**Comment by Bobgy** [comment]
> @Bobgy Only one question here, how can we do if users are filing issues for specific cloud-providers / distributions?

I think we should also add redirects for distributions, a problem might be not all distributions have their own issue board yet. I think each distribution should have a separate one though.

**Comment by kimwnasptd** [comment]
@Bobgy this is really exciting!

**Comment by PatrickXYS** [comment]
> > @Bobgy Only one question here, how can we do if users are filing issues for specific cloud-providers / distributions?
> 
> I think we should also add redirects for distributions, a problem might be not all distributions have their own issue board yet. I think each distribution should have a separate one though.

Yes that's what I was thinking, as a follow, we may need to inform cloud-providers of creating their own one.

**Comment by thesuperzapper** [comment]
As discussed in https://github.com/kubeflow/kubeflow/pull/5585, we should consider setting up an https://issues.kubeflow.org web-app for a longer term solution, the basic idea is:
- I think the right way to go is labels, and a single main repo (`kubeflow/kubeflow`) which stores issues
- this is because lots of issues are not specific to any one part of kubeflow, and need visibility across the Working Groups

The question is, how does the idea for the web app enable users to find/apply the right labels to issues they raise on kubeflow/kubeflow?
- we could have labels automatically applied from the web-app, based on some flow chart (or text analysis if we get them to write the issue directly on the web-app)
- perhaps a bot could auto close issues if they are un-labeled for over 30min
- the user might OAUTH with GitHub on the web-app so we can raise issues on their behalf

Obviously users could still manually add labels in the case they know what they need, or the web-app is down.

**Comment by thesuperzapper** [comment]
/close

This was done in https://github.com/kubeflow/kubeflow/pull/5585
