### ISSUE TITLE
Create web site repo and team

### ISSUE THREAD

**Issue by ewilderj** [kubeflow/community#56]
Could we set up a repo `website` for the Kubeflow web site, and accompanying team on Github to coordinate around it. Myself and @nickchase would happily act as admins on this.

ref #21

**Comment by jlewi** [comment]
I created the repository. Edd I made you and Admin.
You should create an owners file so that Prow can handle issues.

Are you sure @nickchase is the right id? Doesn't look like he's a member of the org.

I didn't create a GitHub team because  access to the repo can be administered via the OWNERs files.
