### ISSUE TITLE
Deprecate the monthly "Kubeflow Feature Store SIG Meeting (US/Asia friendly)" call

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/community#630]
Follow up of https://github.com/kubeflow/community/pull/629
and https://github.com/kubeflow/community/issues/619

“KFServing Working Group US/EU” should be long gone as well

@kimwnasptd @annajung @DnPlas

**Comment by juliusvonkohout** [comment]
according to @jbottum also the product manager meeting

**Comment by thesuperzapper** [comment]
@juliusvonkohout I have raised PR https://github.com/kubeflow/community/pull/639 which will remove the "Feature Store SIG Meeting".

But I have had to manually delete the "model sig" and "kfserving" ones, because people mistakenly removed them from the calendar file, rather than setting an end date. (Which usually results in my email being spammed with thousands of "failed to deliver" messages, because for some reason, deleting the meeting sends an email to all members).
