### ISSUE TITLE
Adoption of Spark-on-k8s-operator

### ISSUE THREAD

**Issue by mwielgus** [kubeflow/community#648]
We are looking for a new home for [Spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator). The project was quite active for years, delivering a convenient way of running Spark in the Kubernetes environment. Unfortunately, due to some org changes, the previous maintainers are unable to provide enough time and love the project and its users deserve. So, GoogleCloudPlatform would like to transfer ownership of the code (already on the Apache license) to an organisation that would help to bring more life to the project and continue to help users run Spark on K8S. Given that you support a wide variety of ML/batch frameworks (MPI, TF, Pytorch etc) we think that Kubeflow would be a good place for the Spark operator.

**Comment by mwielgus** [comment]
cc: @terrytangyuan

**Comment by terrytangyuan** [comment]
+1 happy to sponsor this. This would be a great addition to the Kubeflow community. cc @james-jwu @theadactyl

**Comment by andreyvelich** [comment]
Thank you for proposing this @mwielgus!

I agree, that Spark operator might be useful for Kubeflow users who want to do Data Preparation, Feature extraction, Data Validation, etc. before building and training their ML models. Currently, Kubeflow doesn't offer such functionality.

It would be nice if you could join our [upcoming AutoML and Training WG Community ](https://docs.google.com/document/d/1MChKfzrKAeFRtYqypFbMXL6ZIc_OgijjkvbqmwRV-64/edit#heading=h.o8oe6e5kry87) call today (September 6th) at 6pm UTC (10am PST) to discuss the details and potential use-cases.

cc @kubeflow/wg-training-leads @tenzen-y @kuizhiqing

**Comment by johnugeorge** [comment]
Is this proposal to haev Spark operator to be independent operator in Kubeflow?

**Comment by mwielgus** [comment]
Thanks, I will join the meeting today :).

**Comment by tenzen-y** [comment]
Basically, SGTM. However, I have the same question as @johnugeorge said.

**Comment by jbottum** [comment]
FYI, The Kubeflow User Survey(s) have consistently shown that users would like a Spark / Kubeflow integration.

**Comment by jbottum** [comment]
We will discuss if and how Kubeflow will support a Spark K8s training operator in our Community Meeting on Tuesday, please find the bridge in these meeting notes.    I suspect there maybe several operators or implementations and we need to decide if we are going to pick one, how it will be support, if it is part of a (new) Kubeflow Working Group, how it is installed, etc.     @kimwnasptd @mwielgus  https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit.  
<img width="661" alt="Screenshot 2023-09-06 at 1 20 29 PM" src="https://github.com/kubeflow/community/assets/10553232/4701e2d1-6f3b-4fcd-ab2e-fdb3b21be2a4">

**Comment by juliusvonkohout** [comment]
[mwielgus](https://github.com/mwielgus) we had a spark operator before. Are they using the modern sparkconnect? https://spark.apache.org/docs/latest/spark-connect-overview.html

You can already use the kubernetes apiserver as spark master. So i am wondering whether that + spark-connect is alaready enough. Anyway i am open to contributions in manifests/contrib.

**Comment by andreyvelich** [comment]
Here is the recording for our initial discussion on Sep 9th around Spark Operator in Kubeflow: https://youtu.be/3D2h5OUNCQo.

@mwielgus Please can you attend Kubeflow Community call **today at 8:00am PST,** so we can have a followup discussion around Spark Operator: https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit#heading=h.xtqde2br5mh4.

cc @kubeflow/wg-training-leads

**Comment by mwielgus** [comment]
@andreyvelich I will be there.

**Comment by andreyvelich** [comment]
Thank you, Marcin!

**Comment by jbottum** [comment]
As a follow-up to our recent Apache Spark discussions in the Kubeflow Community meetings, we are requesting some user input... If you are a Spark user or contributor, the Kubeflow Community would like to know if you need active support for a Spark Kubernetes Operator.   If so, would you please comment or +1 on this GitHub issue.   We need at least 10 users and would appreciate any ideas on use cases i.e. integration with notebooks or Kubeflow pipelines.   Thanks!   Josh

**Comment by droctothorpe** [comment]
IMO, the fundamental gap is the lack of an SDK. Data scientists would rather write python than yaml (for good reason). There needs to be (a) some clarification (and documentation) about the benefits of the spark operator over pyspark, and (b) development of an SDK (perhaps an extension to the training operator SDK).

**Comment by charlesa101** [comment]
@droctothorpe, We currently use the SparkOperator in a few of our projects, It makes it easy for us to deploy Spark Jobs "natively" on K8s, more like how the training operators currently work, so I am not sure what you mean by lack of SDK here. 

We use it with Kubeflow Pipeline DSL

```def spark_hello_world_pipeline(jar_location="gcs://....",):
    spark_json_template = Template("""
{
    "apiVersion": "sparkoperator.k8s.io/v1beta2",
    "kind": "SparkApplication",
    "metadata": {
      "name": "hello-pipeline",
      "namespace": "kubeflow"},
    "spec": {
      "type": "Scala",
      "mode": "cluster",
      "mainApplicationFile": "$jar_location"
    }""")
    spark_json = spark_json_template.substitute({'jar_location': jar_location})
    spark_job = json.loads(spark_json)
    spark_resource = dsl.ResourceOp(
        name='spark-job',
        k8s_resource=spark_job,
        success_condition='status.state == Succeeded')
...
```

+1 on this issue, It will be great for SparkOperator to find a new home here

**Comment by droctothorpe** [comment]
@charlesa101 that's json with no customization, and the configuration options are [abundant](https://spark.apache.org/docs/latest/running-on-kubernetes.html#configuration). It's nice to be able to just use ResourceOp though. Thanks for sharing. 

Our platform provides both pyspark and Spark Operator support, and the overwhelming majority of users prefer pyspark. That's just one data point though. IMO, a proper, python interface ala the training operator (or pyspark) would promote adoption.

**Comment by charlesa101** [comment]
@droctothorpe This is based on CRD for SparkOperator, This will work in the same way for PySpark. I'm curious to know more about how your PySpark Operator implementation works. The configurations are abundant but I am not sure there will be a use case for you to have to load up all the configs

I agree with you that It will be great to eventually align the behavior of this operator with the training operators to make it easy to use but I am not sure what you still mean by SDK in this context! Once you have the YAML and CRDs well-defined you can easily use them in your KFP as a component

**Comment by terrytangyuan** [comment]
Here's the Python SDK for training-operator. Basically instead of writing YAML and use it in your KFP component, you can use Python to define and submit jobs directly.

**Comment by charlesa101** [comment]
Oh I see what you mean, thanks @terrytangyuan 👍

**Comment by andreyvelich** [comment]
Hi @mwielgus, please can you join [Kubeflow Community call](https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit) next Tuesday on October 31st 8:00am PST ?
We can discuss the next steps and possibilities to move this forward. 

Also @thesuperzapper can share some details around using Spark with Kubeflow Notebooks 2.0 (e.g. Kubeflow Workspaces).

**Comment by mwielgus** [comment]
@andreyvelich Yes, I will be there.

**Comment by andreyvelich** [comment]
We had a great discussion around adoption of Spark Operator during KubeCon with @mwielgus and @vara-bonthu.
We might be able to find folks who can maintain this project moving forward.
Let's have a chat tomorrow during [Kubeflow Community Call (November 14th at 8:00am PST)](https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit#heading=h.bntrw1z2291).

@jbottum We will provide more updates during the call and discuss the next steps.

**Comment by andreyvelich** [comment]
Hi Everyone, as we discussed on the latest Kubeflow community call we started this doc to donate Spark Operator to Kubeflow:
https://docs.google.com/document/d/1rCPEBQZPKnk0m7kcA5aHPf0fISl0MTAzsa4Wg3dfs5M/edit#heading=h.z7wqs2ebrwra
Please take a look and provide your comments.
It would be great if we could quickly discuss it during our today's Kubeflow Community Call at 8am PST. 

cc @kubeflow/project-steering-group @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads @kubeflow/wg-notebooks-leads

**Comment by andreyvelich** [comment]
cc @yuchaoran2011

**Comment by lfrancke** [comment]
If you want the operator to become even semi-"official" it should be donated to the ASF instead.
The ASF - in general - does not give any product the recognition of being the "official X for Y" or the "approved".
(I say this as a member of the ASF but not with any special knowledge or any special powers, just from my knowledge of the policies - especially around trademarks). https://www.apache.org/foundation/marks/

While we're at it: The current name "Google's Spark K8s Operator" might be a violation of the trademark policy already. 
I suggest clarifying with the ASF before adopting the name.
The usual "approved" naming scheme is "XYZ for Apache Foo". In this case: Google's Kubernetes operator for Apache Spark" (or similar)
It needs to be made clear, in naming, documentation and communication that this is in no way officially affiliated with the ASF.

With my other hat - as a co-founder of [Stackable](https://stackable.tech/) I'd like to point to another operator for Apache Spark which already exists (built by us): https://github.com/stackabletech/spark-k8s-operator/ and which we recently [compared](https://stackable.tech/en/spark-on-kubernetes-operators-a-comparison/) to the Google one.

Happy to help with any ASF related communication.

**Comment by wilfred-s** [comment]
I agree with @lfrancke on the point of donating to the ASF if you want to make it even semi official.
In the [Apache YuniKorn](https://yunikorn.apache.org) community we see a number of groups using the operator. Most of them have made changes to the operator to fix issues or integrate with newer versions of Apache Spark.

**Comment by terrytangyuan** [comment]
> If you want the operator to become even semi-"official" it should be donated to the ASF instead.

IMO, "official" should only be earned by merit and community adoption. Although donating to ASF helps the legal side, CNCF provides a good community around K8s and cloud-native technologies.

> With my other hat - as a co-founder of [Stackable](https://stackable.tech/) I'd like to point to another operator for Apache Spark which already exists (built by us): https://github.com/stackabletech/spark-k8s-operator/ and which we recently [compared](https://stackable.tech/en/spark-on-kubernetes-operators-a-comparison/) to the Google one.

Out of curiosity, why not join the effort of maintaining the existing Spark Operator that's already widely adopted?

**Comment by thesuperzapper** [comment]
I don't think this discussion is about trying to present the Google Spark operator as an "official" option (from a Spark or even a Kubeflow perspective), it's simply about giving a new home for the existing users and contributors of [`GoogleCloudPlatform/spark-on-k8s-operator`](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) on the Kubeflow org, so they can continue working on it in a neutral place, rather than continue struggling under their current home.

It's up to the maintainers of `GoogleCloudPlatform/spark-on-k8s-operator` to decide where they want to live, and in this specific case, it seems like they need a solution in the short-term solution to prevent those contributors/users from being stuck and unable to continue development.

Longer term, there is a strategic question about whether all three operators can be merged (including the [Stackable one](https://github.com/stackabletech/spark-k8s-operator) and the one that [Apple was proposing to donate to the ASF](https://docs.google.com/document/d/1f5mm9VpSKeWC72Y9IiKN2jbBn32rHxjWKUfLRaGEcLE/edit#heading=h.h3pualbnwuc2)), but I don't think that needs to block this donation, if all parties are willing.

**Comment by Jeffwan** [comment]
Hi forks, long time no see due to busy internal work. I happen to see this thread.  Few things to note

1. spark-operator collaboration has been there for long term. If they need sponsor, Kubeflow would be a perfect umbrella and it would gradually extends to DATA + AI scope. 

2. about "official", I am in Spark dev list and notice there's a proposal there [SPIP : Spark Kubernetes Operator](https://docs.google.com/document/d/1f5mm9VpSKeWC72Y9IiKN2jbBn32rHxjWKUfLRaGEcLE/edit#heading=h.h3pualbnwuc2). Honestly, I think the GCP version is pretty good and widely used by numerous users and orgs. If kubeflow community can drive its evolvement, that help a lots of Spark users and may avoid reinventing wheels.

**Comment by vara-bonthu** [comment]
Matthew (@thesuperzapper) makes a good point - we are looking for a new home for Google's Spark Operator, and CNCF projects like Kubeflow seem like a good fit because they have a bigger community. But our main goal is to prevent Apache Spark from making another Java Spark Operator. Instead, we think it's important for everyone to work together on one Spark Operator.

@Jeffwan, you're right. We found a [proposal](https://docs.google.com/document/d/1f5mm9VpSKeWC72Y9IiKN2jbBn32rHxjWKUfLRaGEcLE/edit#heading=h.q3v0khl7opvz)  that already has votes from Spark maintainers. But we added our comments to the proposal, saying that we think Google's Spark Operator is widely adopted by hundreds of organizations in production today. Salesforce and few others also added a "+" and said they think Google's Spark Operator is a good idea.

To make sure the Apache Spark community knows what we're thinking, we started a new proposal (SPIP) inside Apache Spark. You can find it here [SPARK-46054](https://issues.apache.org/jira/browse/SPARK-46054).

Please share your thoughts and vote on the [proposal](https://issues.apache.org/jira/browse/SPARK-46054). We want to work together on one Spark Operator, no matter if it ends up under Apache or Kubeflow. This will make the community bigger and stronger.

@wilfred-s @terrytangyuan with the support from your folks, we can work endorse one tool to bug bigger community.

**Comment by lfrancke** [comment]
> > With my other hat - as a co-founder of [Stackable](https://stackable.tech/) I'd like to point to another operator for Apache Spark which already exists (built by us): [stackabletech/spark-k8s-operator](https://github.com/stackabletech/spark-k8s-operator/) and which we recently [compared](https://stackable.tech/en/spark-on-kubernetes-operators-a-comparison/) to the Google one.
> 
> Out of curiosity, why not join the effort of maintaining the existing Spark Operator that's already widely adopted?

I don't want to derail this issue, so I'll try to keep it short.
Our use-case is different: We are building a platform which includes 10+ tools and operators (I recently gave a [talk](https://www.youtube.com/watch?v=_GJAuwnVBqo) on our experience building a lot of operators). And for us it's important that all operators support the same [features](https://features.stackable.tech/), consolidated [documentation](https://docs.stackable.tech/home/stable/index.html), [CRD docs](https://crds.stackable.tech/), [vulnerability management](https://docs.google.com/document/d/1QB3EaimrS0KlL6wIpfY5-SlEEYV_Y-hfM8_SGKjGNz0/), [supply chain security stuff](https://stackable.tech/en/empowering-rust-projects/), [Cyber Resilience Act compliance](https://docs.google.com/presentation/d/1Be7QYH4ku8ADDZlnULMIWsnLV1MGT7noE0Nc-U5GjEg) etc.
For that reason we made a decision to build our own operators to make sure they all are... similar. I hope that makes sense?

@vara-bonthu As mentioned before: It would be against the ASF rules for a project to "endorse" a project. So that is never going to happen if the project is not part of the ASF itself and even then the term "endorse" would almost certainly not be used.

**Comment by vara-bonthu** [comment]
> @vara-bonthu As mentioned before: It would be against the ASF rules for a project to "endorse" a project. So that is never going to happen if the project is not part of the ASF itself and even then the term "endorse" would almost certainly not be used.

@lfrancke Thank you for the clarification regarding the term "endorse."

To clarify our intent, we have a straightforward goal here. We are interested in investigating the potential donation of the Spark Operator to either the Apache or Kubeflow projects. Once such a donation is agreed upon, we are committed to aligning with and adhering to the governance policies and guidelines of the chosen organization. 

We also aim to prevent the unnecessary duplication of efforts in building multiple Spark Operators, which can potentially lead to confusion among users and organizations.

**Comment by vikas-saxena02** [comment]
I am in support of this proposal as I have done a variety of usecases that require SparkML due to sheer volumes of data including near realtime scenarios using spark streaming. @andreyvelich @jbottum @akgraner  I am more than happy to be part of this initiative as I have the right skills for the same.

**Comment by andreyvelich** [comment]
It's great to hear @vikas-saxena02.
If you are available, please attend one of the upcoming [Kubeflow Community Calls on Tuesday at 8am PST](https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit), so we can discuss the Spark Operator adoption updates.

**Comment by terrytangyuan** [comment]
See https://github.com/kubeflow/spark-operator

/close
