### ISSUE TITLE
RFC: expanding `build/boilerplate/boilerplate.py` for automatically inserting a correct boilerplate

### ISSUE THREAD

**Issue by mitake** [kubeflow/community#9]
As discussed in https://github.com/kubeflow/kubeflow/pull/204, it would be useful if we can expand `build/boilerplate/boilerplate.py` for automatically inserting a correct boilerplate to source files which don't have the boilerplate.

I'd like to know that the kubeflow developers think the feature is useful or not. cc @jlewi

**Comment by jlewi** [comment]
What does it do right now? Does it just print out files that don't have correct boiler plate?

A tool to automatically add the boilerplate seems useful.

Might also be useful to turn it into a check that we could run as part of our prow jobs like
https://github.com/kubeflow/tf-operator/blob/master/py/py_checks.py

**Comment by mitake** [comment]
Currently the script prints out files w/o correct boilerplate like below:
```
$make
>> checking file boilerplate
Boilerplate header is wrong for: /home/mitake/gopath/src/github.com/kubeflow/kubeflow/kubeflow/generate_docs.py
Makefile:17: recipe for target 'presubmit' failed
make: *** [presubmit] Error 1
```

Probably inserting the correct boilerplate to the files wouldn't be complicated if the files are just lacking the boilerplates. So I think it can be a good starting point. The difficult case would be dealing with files which have incorrect boilerplates (e.g. spelling errors). Detecting and removing the incorrect boilerplate isn't trivial at all. How do you think?

**Comment by jlewi** [comment]
My suggestion would be 

1. Add it as a presubmit failure 
2. Add some utilities to add the correct boiler plate.

I think #1 is the most important because of #1; I don't think we have to worry to much edge cases for #2 since people can handle that manually.

For #1, I'd suggest start by adding it as a check in our testing Argo workflow for kubeflow/testing
https://github.com/kubeflow/testing

Then we can see about turning that into a reusable workflow that we can just add to all our repositories (see #11).
